export const COLOR_VARIABLES = {
    cssColorGray00: "#ffffff",
    cssColorGray01: "#fafafa",
    cssColorGray02: "#e7e7e7",
    cssColorGray03: "#dfdfdf",
    cssColorGray04: "#bfbfbf",
    cssColorGray05: "#838383",
    cssColorGray06: "#4b5053",
    cssColorSwell: "#0058b0",
    cssColorWind: "#00aced",
    cssColorPeriod: "#febe53",
    cssColorTide: "#0058b0",
    cssColorNight: "#6694A8",
    cssColorNightDark: "#1E6888",

    // Forecast colors.
    cssColorForecastPossible: "#a7efaf",
    cssColorForecastGood: "#45c46f",
    cssColorForecastVeryGood: "#1a9342",
    cssColorForecastEpic: "#0a3d1b",

    // cssColorChartAframe: globalStyle.getPropertyValue('--color-chart-pie-aframe'),
    // cssColorChartRight: globalStyle.getPropertyValue('--color-chart-pie-right'),
    // cssColorChartLeft: globalStyle.getPropertyValue('--color-chart-pie-left'),
    // cssColorChartSand: globalStyle.getPropertyValue('--color-chart-pie-sand'),
    // cssColorChartSandRocks: globalStyle.getPropertyValue('--color-chart-pie-sand-rocks'),
    // cssColorChartRocks: globalStyle.getPropertyValue('--color-chart-pie-rocks'),
    // cssColorChartRocksSand: globalStyle.getPropertyValue('--color-chart-pie-rocks-sand'),
    // cssColorChartReef: globalStyle.getPropertyValue('--color-chart-pie-reef'),
    // cssColorChartReefSand: globalStyle.getPropertyValue('--color-chart-pie-reef-sand'),
    // cssColorChartBoulders: globalStyle.getPropertyValue('--color-chart-pie-boulders'),
    // cssColorChartCobbles: globalStyle.getPropertyValue('--color-chart-pie-cobbles'),
    // cssFontMain: globalStyle.getPropertyValue('--font-family-main'),
    // cssFontHeadings: globalStyle.getPropertyValue('--font-family-headings'),
    // cssChartDirectionLabelSize: globalStyle.getPropertyValue('--chart-direction-label-size'),
    // cssChartBarLabelSize: globalStyle.getPropertyValue('--chart-bar-label-size'),
    // cssChartBarLabelSizeSmall: globalStyle.getPropertyValue('--chart-bar-label-size-small'),
    // cssChartLineLabelSize: globalStyle.getPropertyValue('--chart-line-label-size'),
    // cssDesktopBreakpoint: parseInt(globalStyle.getPropertyValue('--desktop-breakpoint'))
};